[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#181616"
foreground = "#c5c8c6"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "IBM Plex Mono"

[general]
live_config_reload = true
